### ISSUE TITLE
Can't push ruby twitter.rb 

### ISSUE THREAD

**Issue by vladkls** [tomiwaAdey/twitter_script#1]
I'm trying to push the app, but have this error in my terminal, any ideas? 

`WARN Selenium [DEPRECATION] Selenium support for PhantomJS is deprecated. Use headless Chrome/Firefox or HTMLUnit instead.
`

**Comment by tomiwaAdey** [comment]
It seems Watir has dropped support for PhantomJS. I'll update the script to use headless chrome instead. 

To use headless chrome (Mac)
1. Install homebrew: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
You'll have to wait a while for homebrew to install. 

2. type `brew install chromedriver`

3. change all the lines 53, 68, 97
from 
`browser = Watir::Browser.new :phantomjs`
to 
`browser = Watir::Browser.new :chrome, {headless: true}`

**Comment by vladkls** [comment]
Well, I've changed, no errors this time, but when I try to rule the "ruby twitter.rb &" command, looks like there is a process ruling and then gets me the text 

[1] 29943

does it make any sense to you? (remind: completely non-technical, first lines of code in my life, sorry)

I've tried to rule the process [for this tweet ](https://twitter.com/McDonaldsCorp/status/933938231472771072), and I've even tried just an account, still didn't work. 

what I'm trying to do is to extract RTs and Favorites from the tweet, let me know if there is this possibility as well. thanks a bunch for the help!

**Comment by tomiwaAdey** [comment]
Yup! That shows that it's working. 

You can also type "ruby twitter.rb" without the "&" so you can see the output. 

You've done well :) 

There's no function right now to extract RTs and favourites, but now you mention it, I'll add a function to do that when I have time.

Anytime Vlad.

**Comment by vladkls** [comment]
Yes, but still nothing changes in my spreadsheet, it's completely blank :(, maybe I've done something wrong 

should I add the columns myself, or the script automatically creates them?

**Comment by tomiwaAdey** [comment]
Which method are you using?

**Comment by vladkls** [comment]
initialize_from_gsheet, the 190 line

**Comment by tomiwaAdey** [comment]
Do you have a list of Twitter profile URLs are in the first column of your spreadsheet? 

Point 3  [in the "Get leads details" readme](https://github.com/tomiwaAdey/twitter_script#get-lead-details-from-a-list-of-twitter-profile-urls-in-a-google-sheet )

**Comment by asseto** [comment]
Can you write what to install instead of Homebrew on Windows ? And how to do that?

**Comment by photboard** [comment]
Is there homebrew alternative for Windows 7?
Can you write how to change for Windows 7 plz?

**Comment by paultrafic** [comment]
I was having the same issue as Vlad w/ Watir not working. I installed chromedriver and changed the code on the lines of code you suggested but am still getting this error: 

`/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- watir (LoadError)from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
`
